# Generated by Django 4.0.4 on 2022-06-07 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, unique=True)),
                ('nutriscore', models.IntegerField()),
                ('nutrigrade', models.CharField(default='', max_length=1)),
                ('url', models.CharField(default='', max_length=255)),
                ('image_url', models.CharField(default='', max_length=255)),
                ('salt', models.FloatField(default=0)),
                ('sugar', models.FloatField(default=0)),
                ('calories', models.FloatField(default=0)),
                ('fat', models.FloatField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.category')),
            ],
        ),
    ]
